## Installation des librairies, chargement des données train.csv et qlq manipulations pour comprendre la structure des commentaires

In [4]:
!pip install tensorflow-cpu==2.17.0 pandas matplotlib scikit-learn

  Using cached tensorflow_cpu-2.17.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 1.2 MB/s eta 0:00:00ta 0:00:01
  Using cached matplotlib-3.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
  Using cached scikit_learn-1.7.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (11 kB)
  Using cached absl_py-2.3.1-py3-none-any.whl.metadata (3.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-25.9.23-py2.py3-none-any.whl.metadata (875 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached h5py-3.15.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.0 kB)
  Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
  Using cached ml_dtypes-0.4.1-cp312-cp3

In [5]:
import os 
import pandas as pd
import tensorflow as tf
import numpy as np

2025-11-19 17:24:50.719627: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
df = pd.read_csv(
    os.path.join('archive','train.csv')
)

In [9]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [10]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [11]:
df.iloc[0]

id                                                0000997932d777bf
comment_text     Explanation\nWhy the edits made under my usern...
toxic                                                            0
severe_toxic                                                     0
obscene                                                          0
threat                                                           0
insult                                                           0
identity_hate                                                    0
Name: 0, dtype: object

In [16]:
df.iloc[10000]['comment_text']

"Hi RedRose and apologies for delay. Here is a draft of what I propose to present on the 'new section' pages.\nThe 6 volumes of Ultimate Allocations cover the 'reported' allocations of all British Railways: Steam  Diesel & Electric Locomotives on BR stock from 1950 - 1968 with additional information from 1948 where available. They are formatted in A4 comb bound volumes for ease of use. There are 3 main columns which are sub-divided with individual locomotive details including date when 'new' if appropriate. All 'reported' and published allocations and re-allocations combined with withdrawal dates where known are listed on either 'Weekly' - 'Monthly' - or 'Period Ending' dependant on regional variations at that time. A link to several testimonials and scanned images type of information provided can be found at www.ultimate-allocations.co.uk\nPlease advise if this information would be acceptable for presentation in the 'new section' you previously advised. I look forward to seeing your r

In [17]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [20]:
df[df.columns[2:]].iloc[50]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 50, dtype: int64

### Ok… je ne savais pas que les comms étaient aussi toxiques… désolé pour ce que vous allez lire ensuite ...

In [21]:
df[df['toxic']==1].head()

id                                       comment_text  \
6   0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
12  0005c987bdfc9d4b  Hey... what is it..\n@ | talk .\nWhat is it......   
16  0007e25b2121310b  Bye! \n\nDon't look, come or think of comming ...   
42  001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
43  00190820581d90ce           FUCK YOUR FILTHY MOTHER IN THE ASS, DRY!   

    toxic  severe_toxic  obscene  threat  insult  identity_hate  
6       1             1        1       0       1              0  
12      1             0        0       0       0              0  
16      1             0        0       0       0              0  
42      1             0        1       0       1              1  
43      1             0        1       0       1              0

In [22]:
df[df['severe_toxic']==1].head()

id                                       comment_text  \
6    0002bcb3da6cb337       COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK   
55   0020e7119b96eeeb  Stupid peace of shit stop deleting my stuff as...   
181  006e87872c8b370c  you are a stupid fuck \n\nand your mother's cu...   
442  01208d2b76624130       Hi \n\nIm a fucking bitch.\n\n50.180.208.181   
579  018663f910e0bfe6  What a motherfucking piece of crap those fuckh...   

     toxic  severe_toxic  obscene  threat  insult  identity_hate  
6        1             1        1       0       1              0  
55       1             1        1       0       1              0  
181      1             1        1       0       1              0  
442      1             1        1       0       1              0  
579      1             1        1       0       1              0

In [23]:
df.iloc[181]['comment_text']

"you are a stupid fuck \n\nand your mother's cunt stinks"

In [24]:
df.iloc[442]['comment_text']

'Hi \n\nIm a fucking bitch.\n\n50.180.208.181'

In [25]:
df.iloc[55]['comment_text']

'Stupid peace of shit stop deleting my stuff asshole go die and fall in a hole go to hell!'

In [26]:
df[df['identity_hate']==1].head()

id                                       comment_text  \
42   001810bf8c45bf5f  You are gay or antisemmitian? \n\nArchangel WH...   
105  00472b8e2d38d1ea         A pair of jew-hating weiner nazi schmucks.   
176  006b94add72ed61c  I think that your a Fagget get a oife and burn...   
218  008e0818dde894fb  Kill all niggers. \n\nI have hard, that others...   
238  0097dd5c29bf7a15  u r a tw@ fuck off u gay boy.U r smelly.Fuck u...   

     toxic  severe_toxic  obscene  threat  insult  identity_hate  
42       1             0        1       0       1              1  
105      1             0        1       0       1              1  
176      1             0        1       1       1              1  
218      1             0        1       0       1              1  
238      1             0        1       0       1              1

## Ici on va faire du pré processing de la data :)

In [29]:
from tensorflow.keras.layers import TextVectorization

In [31]:
x = df['comment_text']
y = df[df.columns[2:0]].values

In [32]:
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [33]:
y

array([], shape=(159571, 0), dtype=float64)

In [34]:
y = df[df.columns[2:]].values

In [35]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [37]:
MAX_FEATURES = 200000 #nombre de mots dans le vocab

In [38]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length=1800,
                               output_mode='int')

In [39]:
vectorizer.adapt(x.values)

In [41]:
vectorizer('Hello world, life is great')[:5]

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([288, 263, 306,   9, 275])>

In [42]:
vectorized_text = vectorizer(x.values)

2025-11-19 18:25:02.392880: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 2297822400 exceeds 10% of free system memory.


In [43]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [44]:
len(x)

159571

In [45]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [47]:
batch_x, batch_y = dataset.as_numpy_iterator().next()

In [50]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [54]:
train_generator = train.as_numpy_iterator()

In [56]:
train_generator.next()

(array([[ 176,   60,   26, ...,    0,    0,    0],
        [3195,  111,   14, ...,    0,    0,    0],
        [ 197,   13,  586, ...,    0,    0,    0],
        ...,
        [ 353,   33,  104, ...,    0,    0,    0],
        [ 253,   65,   29, ...,    0,    0,    0],
        [   1,  136, 3666, ...,    0,    0,    0]]),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]))

## Création du Sequential Model